-- A executer une seule fois dans Supabase > SQL Editor.
create table if not exists public.visitors (
    id bigint generated by default as identity primary key,
    visited_at timestamptz not null default now()
);

alter table public.visitors enable row level security;

drop policy if exists "Allow public visitor inserts" on public.visitors;
create policy "Allow public visitor inserts"
on public.visitors for insert
to anon, authenticated
with check (true);

drop policy if exists "Allow public visitor count" on public.visitors;
create policy "Allow public visitor count"
on public.visitors for select
to anon, authenticated
using (true);
